/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TosRouteImport } from './routes/tos'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DevelopersRouteImport } from './routes/developers'
import { Route as DeveloperRouteImport } from './routes/developer'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoomsSessionIdRouteImport } from './routes/rooms.$sessionId'
import { Route as DiscordInstallRouteImport } from './routes/discord.install'
import { Route as DeveloperLoginRouteImport } from './routes/developer.login'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as ApiV1RoomsRouteImport } from './routes/api.v1.rooms'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'

const TosRoute = TosRouteImport.update({
  id: '/tos',
  path: '/tos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersRoute = DevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperRoute = DeveloperRouteImport.update({
  id: '/developer',
  path: '/developer',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsSessionIdRoute = RoomsSessionIdRouteImport.update({
  id: '/rooms/$sessionId',
  path: '/rooms/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscordInstallRoute = DiscordInstallRouteImport.update({
  id: '/discord/install',
  path: '/discord/install',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperLoginRoute = DeveloperLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => DeveloperRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1RoomsRoute = ApiV1RoomsRouteImport.update({
  id: '/api/v1/rooms',
  path: '/api/v1/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/developer': typeof DeveloperRouteWithChildren
  '/developers': typeof DevelopersRoute
  '/docs': typeof DocsRoute
  '/privacy': typeof PrivacyRoute
  '/tos': typeof TosRoute
  '/auth/login': typeof AuthLoginRoute
  '/developer/login': typeof DeveloperLoginRoute
  '/discord/install': typeof DiscordInstallRoute
  '/rooms/$sessionId': typeof RoomsSessionIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/rooms': typeof ApiV1RoomsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/developer': typeof DeveloperRouteWithChildren
  '/developers': typeof DevelopersRoute
  '/docs': typeof DocsRoute
  '/privacy': typeof PrivacyRoute
  '/tos': typeof TosRoute
  '/auth/login': typeof AuthLoginRoute
  '/developer/login': typeof DeveloperLoginRoute
  '/discord/install': typeof DiscordInstallRoute
  '/rooms/$sessionId': typeof RoomsSessionIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/rooms': typeof ApiV1RoomsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/developer': typeof DeveloperRouteWithChildren
  '/developers': typeof DevelopersRoute
  '/docs': typeof DocsRoute
  '/privacy': typeof PrivacyRoute
  '/tos': typeof TosRoute
  '/auth/login': typeof AuthLoginRoute
  '/developer/login': typeof DeveloperLoginRoute
  '/discord/install': typeof DiscordInstallRoute
  '/rooms/$sessionId': typeof RoomsSessionIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/rooms': typeof ApiV1RoomsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/developer'
    | '/developers'
    | '/docs'
    | '/privacy'
    | '/tos'
    | '/auth/login'
    | '/developer/login'
    | '/discord/install'
    | '/rooms/$sessionId'
    | '/api/auth/$'
    | '/api/v1/rooms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/developer'
    | '/developers'
    | '/docs'
    | '/privacy'
    | '/tos'
    | '/auth/login'
    | '/developer/login'
    | '/discord/install'
    | '/rooms/$sessionId'
    | '/api/auth/$'
    | '/api/v1/rooms'
  id:
    | '__root__'
    | '/'
    | '/developer'
    | '/developers'
    | '/docs'
    | '/privacy'
    | '/tos'
    | '/auth/login'
    | '/developer/login'
    | '/discord/install'
    | '/rooms/$sessionId'
    | '/api/auth/$'
    | '/api/v1/rooms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DeveloperRoute: typeof DeveloperRouteWithChildren
  DevelopersRoute: typeof DevelopersRoute
  DocsRoute: typeof DocsRoute
  PrivacyRoute: typeof PrivacyRoute
  TosRoute: typeof TosRoute
  AuthLoginRoute: typeof AuthLoginRoute
  DiscordInstallRoute: typeof DiscordInstallRoute
  RoomsSessionIdRoute: typeof RoomsSessionIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiV1RoomsRoute: typeof ApiV1RoomsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tos': {
      id: '/tos'
      path: '/tos'
      fullPath: '/tos'
      preLoaderRoute: typeof TosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers': {
      id: '/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer': {
      id: '/developer'
      path: '/developer'
      fullPath: '/developer'
      preLoaderRoute: typeof DeveloperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/$sessionId': {
      id: '/rooms/$sessionId'
      path: '/rooms/$sessionId'
      fullPath: '/rooms/$sessionId'
      preLoaderRoute: typeof RoomsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discord/install': {
      id: '/discord/install'
      path: '/discord/install'
      fullPath: '/discord/install'
      preLoaderRoute: typeof DiscordInstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer/login': {
      id: '/developer/login'
      path: '/login'
      fullPath: '/developer/login'
      preLoaderRoute: typeof DeveloperLoginRouteImport
      parentRoute: typeof DeveloperRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/rooms': {
      id: '/api/v1/rooms'
      path: '/api/v1/rooms'
      fullPath: '/api/v1/rooms'
      preLoaderRoute: typeof ApiV1RoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DeveloperRouteChildren {
  DeveloperLoginRoute: typeof DeveloperLoginRoute
}

const DeveloperRouteChildren: DeveloperRouteChildren = {
  DeveloperLoginRoute: DeveloperLoginRoute,
}

const DeveloperRouteWithChildren = DeveloperRoute._addFileChildren(
  DeveloperRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DeveloperRoute: DeveloperRouteWithChildren,
  DevelopersRoute: DevelopersRoute,
  DocsRoute: DocsRoute,
  PrivacyRoute: PrivacyRoute,
  TosRoute: TosRoute,
  AuthLoginRoute: AuthLoginRoute,
  DiscordInstallRoute: DiscordInstallRoute,
  RoomsSessionIdRoute: RoomsSessionIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiV1RoomsRoute: ApiV1RoomsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
