/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TosRouteImport } from './routes/tos'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoomsSessionIdRouteImport } from './routes/rooms.$sessionId'
import { Route as DiscordInstallRouteImport } from './routes/discord.install'

const TosRoute = TosRouteImport.update({
  id: '/tos',
  path: '/tos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsSessionIdRoute = RoomsSessionIdRouteImport.update({
  id: '/rooms/$sessionId',
  path: '/rooms/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscordInstallRoute = DiscordInstallRouteImport.update({
  id: '/discord/install',
  path: '/discord/install',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/tos': typeof TosRoute
  '/discord/install': typeof DiscordInstallRoute
  '/rooms/$sessionId': typeof RoomsSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/tos': typeof TosRoute
  '/discord/install': typeof DiscordInstallRoute
  '/rooms/$sessionId': typeof RoomsSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/tos': typeof TosRoute
  '/discord/install': typeof DiscordInstallRoute
  '/rooms/$sessionId': typeof RoomsSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/tos'
    | '/discord/install'
    | '/rooms/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/privacy' | '/tos' | '/discord/install' | '/rooms/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/privacy'
    | '/tos'
    | '/discord/install'
    | '/rooms/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacyRoute: typeof PrivacyRoute
  TosRoute: typeof TosRoute
  DiscordInstallRoute: typeof DiscordInstallRoute
  RoomsSessionIdRoute: typeof RoomsSessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tos': {
      id: '/tos'
      path: '/tos'
      fullPath: '/tos'
      preLoaderRoute: typeof TosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/$sessionId': {
      id: '/rooms/$sessionId'
      path: '/rooms/$sessionId'
      fullPath: '/rooms/$sessionId'
      preLoaderRoute: typeof RoomsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discord/install': {
      id: '/discord/install'
      path: '/discord/install'
      fullPath: '/discord/install'
      preLoaderRoute: typeof DiscordInstallRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacyRoute: PrivacyRoute,
  TosRoute: TosRoute,
  DiscordInstallRoute: DiscordInstallRoute,
  RoomsSessionIdRoute: RoomsSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
